apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubi-user
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubi-user
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kubi-user
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubi-deployment
  namespace: kube-system
  labels:
    app: kubi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubi
  template:
    metadata:
      labels:
        app: kubi
    spec:
      serviceAccountName: kubi-user
      containers:
        - name: kubi
          image: cagip/kubi:1.2.5
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: kubi-tls
              mountPath: "/var/run/secrets/certs"
              readOnly: true
          envFrom:
            - configMapRef:
                name: kubi-config
          env:
            - name: LDAP_PASSWD
              valueFrom:
                secretKeyRef:
                  name: kubi-secret
                  key: ldap_passwd
      volumes:
        - name: kubi-tls
          secret:
            secretName: kubi
---
apiVersion: v1
kind: Service
metadata:
  name: kubi-svc
  namespace: kube-system
  labels:
    app: kubi
spec:
  type: NodePort
  ports:
    - name: https
      port: 8000
      targetPort: 8000
      protocol: TCP
      nodePort: 30003
  selector:
    app: kubi
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubi-reader
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["ca-gip.github.com"]
    resources: ["projects"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    creator: kubi
    name: kubi-reader
  name: kubi-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubi-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: kubi-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    creator: kubi
    name: kubi-reader-discovery
  name: kubi-reader-discovery
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: system:discovery
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: kubi-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    creator: kubi
    name: kubi-reader-basic-user
  name: kubi-reader-basic-user
roleRef:
  apiGroup: ""
  kind: ClusterRole
  name: system:basic-user
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: kubi-reader